# Generated by Django 5.2.4 on 2026-02-04 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/')),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('Contenus Numériques', 'Contenus Numériques'), ('Logiciels & Applications', 'Logiciels & Applications'), ('Formations & Éducation en Ligne', 'Formations & Éducation en Ligne'), ('Création & Média', 'Création & Média'), ('Outils pour Créateurs & Entrepreneurs', 'Outils pour Créateurs & Entrepreneurs'), ('Divertissement & Gaming', 'Divertissement & Gaming'), ('Services Professionnels Digitalisés', 'Services Professionnels Digitalisés'), ('Communautés en Ligne', 'Communautés en Ligne'), ('Produits Tech Avancés', 'Produits Tech Avancés'), ('Investissement & Finance Digitale', 'Investissement & Finance Digitale'), ('Autres types', 'Autres types')], default='Contenus Numériques', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(upload_to='products/')),
                ('likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chargily_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PAN', 'Pending'), ('PAID', 'Paid')], default='PAN', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('Ripcode', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
