# Generated by Django 5.2.4 on 2026-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Ripcode',
            new_name='BaridiMob',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
