# Generated by Django 5.2.4 on 2026-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
