# Generated by Django 5.2.4 on 2026-02-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_commission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commission',
        ),
    ]
