# Generated by Django 5.2.4 on 2026-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_delete_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/photos/userphoto-defaultphoto.png', upload_to='photos/'),
        ),
    ]
